# This is a basic workflow to help you get started with Actions

name: 'Build'

on:
  push:
    branches: [ GeekMail-Pro ]
  pull_request:
    branches: [ GeekMail-Pro ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  releaseJar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Cache .gradle/caches
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Cache .gradle/wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-wrapper-

      - name: 授予 gradlew 的执行权限
        run: chmod +x gradlew

      # 第一次构建
      - name: build
        id: build_1
        run: ./gradlew build
      # 第二次构建
      - name: build (retry 1)
        id: build_2
        if: steps.build_1.outcome == 'failure'
        run: ./gradlew build
      # 第三次构建
      - name: build (retry 2)
        id: build_3
        if: steps.build_2.outcome == 'failure'
        run: ./gradlew build
      # 第四次构建
      - name: build (retry 3)
        id: build_4
        if: steps.build_3.outcome == 'failure'
        run: ./gradlew build

      - name: 上传工件
        uses: actions/upload-artifact@v2
        with:
          name: GeekMail-Pro Artifact
          path: build/libs/*.jar
